print("Welcome to the Band Name Generator.")
home_town = input("What is the name of the city you grew up in?\n")
print(home_town)
pet_name = input("What is your pet's name?\n")
print(pet_name)
print("Your band could be " + home_town + " " + pet_name + ".")